# Generated by Django 4.0.4 on 2022-05-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_category_remove_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('C', 'construction'), ('W', 'welding'), ('G', 'general'), ('P', 'paints')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('C', 'construction'), ('W', 'welding'), ('G', 'general'), ('P', 'paints')], max_length=1, null=True),
        ),
    ]
